import { type Transaction } from "./features/transactions/types";

export const mockTransactions: Transaction[] = [
  {
    id: "txn_001",
    description: "Netflix Subscription",
    amount: 1400,
    type: "expense",
    category: "Entertainment",
    date: "2025-10-12",
    status: "completed",
  },
  {
    id: "txn_002",
    description: "Freelance Payment - October",
    amount: 35000,
    type: "income",
    category: "Income",
    date: "2025-10-15",
    status: "completed",
  },
  {
    id: "txn_003",
    description: "Grocery Store - Weekly",
    amount: 4200,
    type: "expense",
    category: "Food",
    date: "2025-10-18",
    status: "completed",
  },
  {
    id: "txn_004",
    description: "Electricity Bill",
    amount: 3100,
    type: "expense",
    category: "Utilities",
    date: "2025-10-21",
    status: "completed",
  },
  {
    id: "txn_005",
    description: "Bus Pass Recharge",
    amount: 1200,
    type: "expense",
    category: "Transport",
    date: "2025-10-23",
    status: "pending",
  },
  {
    id: "txn_006",
    description: "Pharmacy Purchase",
    amount: 900,
    type: "expense",
    category: "Health",
    date: "2025-10-28",
    status: "completed",
  },
  {
    id: "txn_007",
    description: "Online Shopping - Headphones",
    amount: 4800,
    type: "expense",
    category: "Shopping",
    date: "2025-11-02",
    status: "completed",
  },
  {
    id: "txn_008",
    description: "Salary - November",
    amount: 50000,
    type: "income",
    category: "Income",
    date: "2025-11-01",
    status: "completed",
  },
  {
    id: "txn_009",
    description: "Dinner with Friends",
    amount: 2300,
    type: "expense",
    category: "Food",
    date: "2025-11-06",
    status: "completed",
  },
  {
    id: "txn_010",
    description: "Ride Share",
    amount: 750,
    type: "expense",
    category: "Transport",
    date: "2025-11-09",
    status: "failed",
  },
  {
    id: "txn_011",
    description: "Internet Bill",
    amount: 1800,
    type: "expense",
    category: "Utilities",
    date: "2025-11-12",
    status: "completed",
  },
  {
    id: "txn_012",
    description: "Movie Tickets",
    amount: 1600,
    type: "expense",
    category: "Entertainment",
    date: "2025-11-15",
    status: "pending",
  },
  {
    id: "txn_013",
    description: "Gym Membership",
    amount: 2500,
    type: "expense",
    category: "Health",
    date: "2025-11-20",
    status: "completed",
  },
  {
    id: "txn_014",
    description: "Dividend Credit",
    amount: 6200,
    type: "income",
    category: "Income",
    date: "2025-11-25",
    status: "completed",
  },
  {
    id: "txn_015",
    description: "Gift Purchase",
    amount: 3400,
    type: "expense",
    category: "Shopping",
    date: "2025-12-03",
    status: "completed",
  },
  {
    id: "txn_016",
    description: "Coffee Shop",
    amount: 480,
    type: "expense",
    category: "Food",
    date: "2025-12-05",
    status: "completed",
  },
  {
    id: "txn_017",
    description: "Water Bill",
    amount: 1100,
    type: "expense",
    category: "Utilities",
    date: "2025-12-09",
    status: "completed",
  },
  {
    id: "txn_018",
    description: "Train Ticket",
    amount: 950,
    type: "expense",
    category: "Transport",
    date: "2025-12-12",
    status: "completed",
  },
  {
    id: "txn_019",
    description: "Year-End Bonus",
    amount: 20000,
    type: "income",
    category: "Income",
    date: "2025-12-20",
    status: "completed",
  },
  {
    id: "txn_020",
    description: "Doctor Consultation",
    amount: 1500,
    type: "expense",
    category: "Health",
    date: "2025-12-23",
    status: "pending",
  },
  {
    id: "txn_021",
    description: "Streaming Bundle",
    amount: 2100,
    type: "expense",
    category: "Entertainment",
    date: "2026-01-04",
    status: "completed",
  },
  {
    id: "txn_022",
    description: "Salary - January",
    amount: 50000,
    type: "income",
    category: "Income",
    date: "2026-01-01",
    status: "completed",
  },
  {
    id: "txn_023",
    description: "Supermarket Essentials",
    amount: 3900,
    type: "expense",
    category: "Food",
    date: "2026-01-08",
    status: "completed",
  },
  {
    id: "txn_024",
    description: "Mobile Recharge",
    amount: 699,
    type: "expense",
    category: "Other",
    date: "2026-01-11",
    status: "failed",
  },
  {
    id: "txn_025",
    description: "Office Commute",
    amount: 1300,
    type: "expense",
    category: "Transport",
    date: "2026-01-14",
    status: "completed",
  },
  {
    id: "txn_026",
    description: "Home Decor Purchase",
    amount: 5600,
    type: "expense",
    category: "Shopping",
    date: "2026-02-02",
    status: "completed",
  },
  {
    id: "txn_027",
    description: "Salary - February",
    amount: 50000,
    type: "income",
    category: "Income",
    date: "2026-02-01",
    status: "completed",
  },
  {
    id: "txn_028",
    description: "Gas Bill",
    amount: 1700,
    type: "expense",
    category: "Utilities",
    date: "2026-02-06",
    status: "pending",
  },
  {
    id: "txn_029",
    description: "Concert Ticket",
    amount: 4200,
    type: "expense",
    category: "Entertainment",
    date: "2026-02-10",
    status: "completed",
  },
  {
    id: "txn_030",
    description: "Medical Tests",
    amount: 2800,
    type: "expense",
    category: "Health",
    date: "2026-02-18",
    status: "completed",
  },
  {
    id: "txn_031",
    description: "Freelance Payment - March",
    amount: 18000,
    type: "income",
    category: "Income",
    date: "2026-03-05",
    status: "completed",
  },
  {
    id: "txn_032",
    description: "Groceries - Monthly",
    amount: 6100,
    type: "expense",
    category: "Food",
    date: "2026-03-09",
    status: "completed",
  },
  {
    id: "txn_033",
    description: "Taxi to Airport",
    amount: 2200,
    type: "expense",
    category: "Transport",
    date: "2026-03-13",
    status: "completed",
  },
  {
    id: "txn_034",
    description: "Utility Maintenance",
    amount: 2400,
    type: "expense",
    category: "Other",
    date: "2026-03-16",
    status: "failed",
  },
  {
    id: "txn_035",
    description: "Salary - March",
    amount: 50000,
    type: "income",
    category: "Income",
    date: "2026-03-01",
    status: "completed",
  },
];
